### PR TITLE
Implement partial function application

### PR DESCRIPTION
**Pull request by thekid**
## Examples

This code:
```php
class Person {
  public function __construct(public int $id, public string $name) { }
}

// Returns an array of three Handle instances
$handles= array_map(fn($_) => new Handle($_), [STDIN, STDOUT, STDERR]);

// Use time() function in production, specialized testing clock for unit tests
$time= $test ? new TestingClock() : 'time';

// Executes HTTP request, then returns a function to read the given input stream
$in= $http->get()->in();
$read= fn() => Streams::readAll($in);

// Creates instances from database records and writes them to the console
Sequence::of($conn->query('select * from person'))
  ->map(fn($_) => new Person(...$_))
  ->each(fn($_) => Console::writeLine('> ', $_))
;
```

...can be rewritten to:
```php
class Person {
  public function __construct(public int $id, public string $name) { }
  public static function from($record) { return new self(...$record); }
}

// Returns an array of three Handle instances
$handles= array_map(new Handle(?), [STDIN, STDOUT, STDERR]);

// Use time() function in production, specialized testing clock for unit tests
$time= $test ? new TestingClock() : time(...);

// Executes HTTP request, then returns a function to read the given input stream
$read= Streams::readAll($http->get()->in(), ...);

// Creates instances from database records and writes them to the console
Sequence::of($conn->query('select * from person'))
  ->map(Person::from(?))
  ->each(Console::writeLine('> ', ?))
;
```

## See also

* https://wiki.php.net/rfc/partial_function_application
* php/php-src#6898
* https://github.com/tc39/proposal-partial-application 
* https://babeljs.io/docs/en/babel-plugin-proposal-partial-application

Depends on xp-framework/ast#26

### CODE REVIEW

**Comment by thekid** [comment]
If we allowed argument unpacking via `...?`, we could further simplify the sequence example:

```php
class Person {
  public function __construct(public int $id, public string $name) { }
}

// Creates instances from database records and writes them to the console
Sequence::of($conn->query('select * from person'))
  ->map(new Person(...?))
  ->each(Console::writeLine('> ', ?))
;
```

**Comment by thekid** [comment]
When we pass around objects as parameters, the placeholder would have to be able to replace the object in something like the following:

```php
$filtered= Sequence::of(...)->filter(fn($user) => $user->isActive());
$filtered= Sequence::of(...)->filter(?->isActive());
```

Hrm...

**Comment by thekid** [comment]
RFC was declined, closing

**Comment by faizanakram99** [comment]
> RFC was declined, closing

it would have been still a nice feature

**Pull request closed without merging**
